NHS-digital-website/hippo

README.md
acceptance-tests/pom.xml
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/AcceptanceTest.java

Through the use of Maven profiles 'cargo.run', 'acceptance-test' and
'acceptance-test-hippo', it is now possible to run automated acceptance
tests against an instance of Hippo CMS that was either started manually,
running constantly in the background, or one that is started and
stopped automatically prior and after the tests, respectively.
The details of how to use the profiles have been described in the
readme.

[RPS-56] Run acc. tests against standalone Hippo instance

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/models/Publication.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/ConsumablePublicationPage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/ContentPage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/ContentSteps.java
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/publication.yaml

Individual geographical coverage options tweaked slightly due to some
values having commas in the text. To revisit. Include test for
selected geographic coverage value.

[RPS-71] Specify geographical coverage for publication

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/ContentPage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/GranularitySection.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/PageHelper.java
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/publication.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/fusce-viverra-dolor.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/lorem-ipsum.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/morbi-tempor-euismod-vehicula.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/morbi-vitae-nunc-ac-lacus-malesuada-tempus.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/nullam-vel-ligula-dapibus.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/nunc-tempus-ante-nec.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/proin-elementum-justo-eu-tortor.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/proin-nec-justo.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/search-test-loremipsumdolor.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/valid-publication-series.yaml

Removed Granularity from:
- publication.yaml prototypes so that an empty placeholder doesn't
get automatically added to newly created documents,
- from the test 'lorem ipsum' documents.
This is a change missed from the main commit 4517457.

[RPS-132] Prevent saving publication with blank Granularity field

---

cms/src/main/java/uk/nhs/digital/ps/BlankStaticDropdownSelectionFieldValidator.java
cms/src/test/java/uk/nhs/digital/ps/BlankStaticDropdownSelectionFieldValidatorTest.java

Even though preValidation throws an exception, the validate method
is still called, so this question has been raised with Bloomreach.

[RPS-141] Fix blankStaticDropdown preValidator error

---

repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/dataset.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl

Removed the resource type indicators for links and files on the publication and the dataset template. Leaving an indicator for datasets on the publication template to distinguish these from links.
Also removed a trailing 'l' that was getting incorrectly added to the end of the publication title.

[RPS-167] wrong resources file type

---

acceptance-tests/src/test/resources/features/site/publication.feature
cms/pom.xml
pom.xml
repository-data/development/src/main/resources/hcm-config/content/taxonomies/publication_taxonomy.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/publication-with-datasets/content.yaml
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/dataset.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl
site/pom.xml
site/src/main/java/uk/nhs/digital/ps/beans/Dataset.java
site/src/main/java/uk/nhs/digital/ps/beans/HippoBeanHelper.java
site/src/main/java/uk/nhs/digital/ps/beans/Publication.java
site/src/main/java/uk/nhs/digital/ps/components/DatasetComponent.java
site/src/main/java/uk/nhs/digital/ps/components/PublicationComponent.java
site/src/test/java/uk/nhs/digital/ps/beans/PublicationTest.java
site/src/test/java/uk/nhs/digital/ps/test/util/ReflectionHelper.java

Moved a number of get methods from DatasetComponent and PublicationComponent to the relevant bean.
This is more object oriented and I've changed the freemarker templates to look at the property directly rather than inserting as a separate variable.
Also added PowerMockito to the project as I needed to mock a static method to simulate queries.

[RPS-170] Refactor properties to beans

---

repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/series.yaml

Removed 'title' that was an unused duplicate of 'Title'.

[RPS-186] Cleaned up series doctype

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/site/ps/DatasetPageElements.java
acceptance-tests/src/test/resources/features/site/datasets.feature
migrator/pom.xml
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/DataSet.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/nesstar/PublishingPackage.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/ImportableItemsFactory.java
migrator/src/main/resources/templates/dataset.json.ftl
migrator/src/main/resources/templates/publication.json.ftl
migrator/src/main/resources/templates/series.json.ftl
migrator/src/test/java/uk/nhs/digital/ps/migrator/model/hippo/DataSetTest.java
repository-data/application/src/main/resources/hcm-config/configuration/update/EximImport.groovy
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/dataset.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/publication-with-datasets/datasets-subfolder/publication-with-datasets-dataset.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/publication-with-datasets/etiam-placerat-arcu-dataset.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/series-with-publication-with-datasets/series-publication-with-datasets/series-publication-with-datasets-dataset.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/upcoming-publication/upcoming-dataset.yaml
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/dataset.ftl
site/src/main/java/uk/nhs/digital/common/components/FacetComponent.java
site/src/main/java/uk/nhs/digital/ps/beans/Dataset.java
site/src/main/java/uk/nhs/digital/ps/beans/HippoBeanHelper.java
site/src/main/java/uk/nhs/digital/ps/beans/Publication.java

Added summary migration for clinical indicators.
Also removed the Purpose field from the CMS as we want the purpose to
just be the last paragraph in the summary.
Also small bit of refactoring to remove duplicate TaxonomyName method.

[RPS-160] Clinical indicator summary migration

---

cms/src/main/java/uk/nhs/digital/ps/CoverageDatesValidator.java
cms/src/test/java/uk/nhs/digital/ps/CoverageDatesValidatorTest.java
repository-data/application/src/main/resources/hcm-config/configuration/frontend/cms-validators.yaml
repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/dataset.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/publication.yaml
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/dataset.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl
site/src/main/java/uk/nhs/digital/ps/directives/CoverageDatesFormatterDirective.java

Added CMS input validation for coverage dates and formatting
of the output dates on the site
- end must not be earlier than start
- start and end dates must be before nominal publication date
- if start and end same, then expressed as 'snapshot on' date
in the rendered publication
- not mandatory, but if one field is populated, then the other
must be populated too (and vice versa)

[RPS-70] Productionise coverage start and end dates

---

migrator/README.md
repository-data/application/src/main/resources/hcm-config/configuration/update/EximImport.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/MigratorImporterScript.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/MigratorImporterScript.yaml

EximImport was re-set to its original version and MigratorImporterScript
was added as THE import script to use to import content generated by
the Migrator application; readme has been updated accordingly.
This is to reflect the fact that MigratorImporterScript is tailored
specifically to consume content generated by the Migrator rather than
more generic output of EximExport.
'FOLDER' JSON files generated by the Migrator application are now being
processed by the import script and so the folders are now created with
display names as specified by property 'jcr:localizedName' in files
generated by the Migrator.
It is now also possible to create empty folders upon migration.

[RPS-204] CI migration: make folder names human-friendly

---

cms/src/main/resources/org/hippoecm/repository/query/lucene/StandardHippoAnalyzer.properties

Set stopwords to use the English (en) locale only

[RPS-212] Fix search bug with stopwords from other locales

---

acceptance-tests/pom.xml
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/site/AbstractSitePage.java
migrator/pom.xml
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/Attachment.java
pom.xml
repository-data/application/src/main/resources/hcm-config/configuration/frontend/cms.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/workspace/channel.yaml
repository-data/application/src/main/resources/hcm-config/hst/hosts.yaml
repository-data/development/src/main/resources/hcm-config/hst/hosts.yaml
src/main/assembly/on-demand-distribution.xml
src/main/assembly/webapps-component.xml

This involves changes to CMS distribution package.
Also:
* fixed migration for Mac OS
* moved non-prod vhosts to `development` module

[RPS-201] Fix preview

---

migrator/src/main/java/uk/nhs/digital/ps/migrator/PublicationSystemMigrator.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/config/ExecutionConfigurator.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/config/ExecutionParameters.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/config/MigratorConfiguration.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/Attachment.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/nesstar/DataSetRepository.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/nesstar/PublishingPackage.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/GenerateNesstarImportContentTask.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/GenerateTaxonomyTask.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/ImportableFileWriter.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/ImportableItemsFactory.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/MigrationTask.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/UnzipNesstarExportFileTask.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/CcgImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/CompendiumImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/NhsOutcomesFrameworkImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/SocialCareImportables.java

The Migrator application now includes in the migrated content
Compendium.
Confluence page 'Structure Mapping' contains Excel spreadsheet, whose
third sheet is used as the source of mapping. Note that while the
structure of this file is expected to not change, its content is a work
in progress and we expect to get updated version(s) of it in the near
future as CI team completes the mapping.
Also, as per the same Confluence page:
Titles of Publications and Series are now generated correctly
accross the board (not just Compendium), that is, they are now set to
the names of appropriate 'ancestor' folders (with appropriate
'Archived' prefixes, where applicable).
Folders immediately under 'root' Compendium folder are now prefixed
with 'Compendium'.

[RPS-192] Migrate CI Compendium

---

acceptance-tests/src/test/resources/features/editScreenValidation.feature
repository-data/application/src/main/resources/hcm-config/configuration/frontend/cms-validators.yaml
repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/publication.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/relatedlink.yaml

Link text for resource links and related links will now be mandatory.
Also removed the custom validation that was only applied to resource
links as it duplicates the behaviour of the build-in validation for
required fields.

[RPS-231] Make Link Text mandatory

---

repository-data/application/src/main/resources/hcm-config/hst/configurations/common/abstractpages/basepage.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/templates.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/components/about.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/pages/about.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/sitemap.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/templates.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem.cnd
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/about.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/about.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/about/terms-and-conditions.yaml
repository-data/development/src/main/resources/hcm-actions.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/about/terms-and-conditions.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/base-footer.ftlh
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/about.ftlh
site/src/main/java/uk/nhs/digital/ps/beans/About.java
site/src/main/java/uk/nhs/digital/ps/components/AboutComponent.java

Added new document type called "About" which will cater for general site
documents such as terms and conditions, accessibility, privacy policy etc. Added
footer component to basepage, along with initial link to terms and conditions document.
Enabled a populated version of terms and conditions document to be bootstraped in the
development module, with a blank document being bootstraped in other environments on
first deployment for the user to populate and maintain (similar to taxonomy). For
subsequent deployments, as the document will already exist, the user maintained version
will not be overwritten.
Note: new document type currently resides under the ps namespace.  Separate ticket to
move this into the common namespace.

[RPS-210] Add terms and conditions

---

repository-data/application/src/main/resources/hcm-config/hst/hosts.yaml
repository-data/development/src/main/resources/hcm-config/hst/hosts.yaml

Set HTTPS to be the default scheme (default was HTTP).
If you visit the http URL you will be redirected to https.
Overwritten this value for AWS and localhost as these envirnoments
don't have certificates set up, therefore this will only affect
OnDemand.

[RPS-227] Enforce HTTPS connections

---

repository-data/application/src/main/resources/hcm-config/hst/configurations/common/templates.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/templates/404.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/templates/base.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/templates/search.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/templates/searchresults.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/templates.yaml
repository-data/application/src/main/resources/hcm-config/main.yaml
repository-data/webfiles/pom.xml
repository-data/webfiles/src/main/resources/site/freemarker/common/404.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/base-footer.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/base-layout.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/base-top-menu.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/facets.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/search.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/searchresults.ftl
repository-data/webfiles/src/main/resources/site/freemarker/include/imports.ftl
repository-data/webfiles/src/main/resources/site/freemarker/include/pagination.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/about.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/dataset.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/folder.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/macro/structured-text.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publications-overview.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/series.ftl
repository-data/webfiles/src/test/java/resources/site/freemarker/FreemarkerFileTest.java
site/src/main/webapp/WEB-INF/web.xml

Revert Freemarker templates back to use *.ftl extension to correct content refresh
issue discovered after RPS-220 (Set Freemarker template MIME type). Output
format and auto escaping is now set directly in the Freemarker template header.
Test added to check all freemarker templates have this directive included as the
first line of the file.

[RPS-248] Fix .ftlh design time content refresh issue

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/ContentPage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/widgets/DateCmsWidget.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/cms/ps/CmsSteps.java
acceptance-tests/src/test/resources/features/cms/datasetValidation.feature
acceptance-tests/src/test/resources/features/cms/publicationValidation.feature
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/dataset.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/publication.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/attachment-test/dataset.yaml

Updated nominal publication date fields on publication and dataset document types
to be mandatory. Added tests to check validation correctly occurs.

[RPS-233] Change nominal publication date to mandatory

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/site/AbstractSitePage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/site/SiteSteps.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/util/TestContentUrls.java
acceptance-tests/src/test/resources/features/site/datasets.feature
acceptance-tests/src/test/resources/features/site/publication.feature
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/attachment-test/dataset.yaml

Added an extra step to the download tests that check the href in the
link for a file download, is what we expect it to be.
This will be able to run in headless mode as well so provides a more
comprehensive test for download links.

[RPS-241] Tests for download URLs

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/site/CommonPageElements.java
acceptance-tests/src/test/resources/features/site/search.feature
repository-data/webfiles/src/main/resources/site/freemarker/include/pagination.ftl

Remove HTML output formatting on the pagination component which caused issues
with paging links. Add acceptance test for pagination link functionality.

[RPS-267] Fix broken pagination links caused by HTML output formatting

---

migrator/src/main/java/uk/nhs/digital/ps/migrator/MigrationReport.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/PublicationSystemMigrator.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/config/MigratorConfiguration.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/Attachment.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/DataSet.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/nesstar/DataSetRepository.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/GenerateNesstarImportContentTask.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/ImportableFileWriter.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/ImportableItemsFactory.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/CompendiumImportables.java
migrator/src/test/java/uk/nhs/digital/ps/migrator/model/hippo/DataSetTest.java

Added reporting on:
- Missed Datasets (e.g. when some are present in Nesstar export but
were missed in manual mapping, such as Compendium).
- Duplicate datasets being written to Hippo import files.
Also, refactored MigrationReport so that it exposes instance methods
rather than static; it is now instantiated and injected from Spring
context.

[RPS-270] CI Migration: report missed data sets

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/site/SitePage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/site/SiteSteps.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/util/TestContentUrls.java
acceptance-tests/src/test/resources/features/site/datasets.feature
acceptance-tests/src/test/resources/features/site/publication.feature
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/bare-minimum-publication.yaml
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl
site/src/main/java/uk/nhs/digital/ps/beans/Publication.java
site/src/main/java/uk/nhs/digital/ps/beans/structuredText/StructuredText.java

Fixed a bug where the Key Facts header would display even when the
Key Facts field was empty. Added tests for the headers not displaying
when the fields are empty and fixed a few other small issues with the
site.

[RPS-278] Empty Key Facts header

---

pom.xml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/relatedlink.yaml
site/src/main/java/uk/nhs/digital/ps/beans/Dataset.java
site/src/main/java/uk/nhs/digital/ps/beans/HippoBeanHelper.java
site/src/main/java/uk/nhs/digital/ps/beans/Publication.java

The field is now mandatory so the hint needed removing.
Also fixed a warning with they code checker by adding a reporting
maven plugin.
Also added some generics missed in my previous PR.

[RPS-257] Removed link text hint

---

ci-cd/bin/set-commit-status
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/nesstar/NesstarResource.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/ImportableItemsFactory.java

Filter out links with set phrases which the CI team do not want
migrated over. This include the following text:
- earlier data may be available
- contact us
As 'contact us' was not found in the nesstar export, if one is
found going forward, it will be logged to the migration report
for attention.

[RPS-289] Filter out certain hyperlinks for CI migration

---

ci-cd/bin/get-hippo-groups-yaml
ci-cd/bin/get-hippo-user-yaml
ci-cd/bin/get-hippo-users-yaml
ci-cd/groups.base.yaml
ci-cd/users.base.yaml
docs/what-if/reset-test-accounts.md

Removed all the hard coded user accounts (including hashed passwords)
except for admin. We are leaving admin with a random hashed password
as this is better than having admin:admin and we will delete the
admin account as soon as we have set up individual accounts in prod.

[RPS-259] Removed hardcoded user accounts

---

migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/Attachment.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/ResourceLink.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/nesstar/NesstarResource.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/report/IncidentType.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/ImportableItemsFactory.java

From now on all links with marker texts are filtered out, regardless
of whether they belong to Compendium or not, but only those that are
from outside Compendium are reported on.
All excluded links and attachments are logged.

[RPS-296] CI migration: modify links filtering

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/site/common/SearchPage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/site/SearchSteps.java
acceptance-tests/src/test/resources/features/site/search.feature
repository-data/webfiles/src/main/resources/site/freemarker/common/search.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/searchresults.ftl
site/src/main/java/uk/nhs/digital/common/components/SearchComponent.java
site/src/test/java/uk/nhs/digital/common/components/SearchComponentTest.java

- Fixed a bug where a search term with an odd number of quotes
caused an error.
- Fixed a display bug where quoted search terms were shown with
escape characters.

[RPS-271] Fixed bugs with searching for quoted terms

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/DashboardPage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/widgets/SearchResultWidget.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/site/SearchSteps.java
acceptance-tests/src/test/resources/features/site/datasets.feature
acceptance-tests/src/test/resources/features/site/publication.feature
acceptance-tests/src/test/resources/features/site/search.feature
acceptance-tests/src/test/resources/features/site/timeSeriesDisplay.feature
ci-cd/Makefile
repository-data/application/src/main/resources/hcm-content/content/documents/administration/publication-system/labels.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/results.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/searchresults.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/dataset.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl
site/src/main/java/uk/nhs/digital/ps/beans/BaseDocument.java
site/src/main/java/uk/nhs/digital/ps/beans/Dataset.java
site/src/main/java/uk/nhs/digital/ps/beans/Publication.java

Also includes refactoring of search result templates to use a separate
macro for each document type.  Fixed issue where dataset nominal
date was not being displayed on search results page. Includes small
change to password rules acceptance test to try resolve random fails.
Update to Makefile to replace publication-system with website.

[RPS-291] Indicate document type of each search result

---

migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/TaxonomyMigrator.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/SocialCareImportables.java
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/about/accessibility-help.yaml

[RPS-316] CI migration: update ASCOF to follow CCG structure
The Migrator now applies folder structure to Social Care/ASCOF CI
content following the same pattern as that used for CCG.
Also:
- TaxonomyMigrator was updated to handle the latest format of Taxonomy
definition spreadsheet.
- Accessibility page has been 'unflaged' as being held by admin
so that it no longer opens by default when admin logs into CMS.

[RPS-316] CI migration: update ASCOF to follow CCG structure

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/ContentPage.java
acceptance-tests/src/test/resources/features/site/clinicalIndicatorsHub.feature
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/pages/cihub.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/sitemap.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/templates.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/pages/cilanding.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/sitemap.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/publicationsystem/templates.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem.cnd
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/cihub.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/cihublink.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/cilanding.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/publication-system/headers.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/ci-hub.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/about/terms-and-conditions.yaml
repository-data/development/src/main/script/YamlFormatter.groovy
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/cihub.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/cilanding.ftl
repository-data/webfiles/src/main/resources/site/less/style.less
site/src/main/java/uk/nhs/digital/ps/beans/CiHub.java
site/src/main/java/uk/nhs/digital/ps/beans/CiHubLink.java
site/src/main/java/uk/nhs/digital/ps/beans/CiLanding.java
site/src/main/java/uk/nhs/digital/ps/components/CiHubComponent.java
site/src/main/java/uk/nhs/digital/ps/components/CiLandingComponent.java
styleguide/ci-hub.html
styleguide/ci-landing-page.html
styleguide/css/style.css
styleguide/index.html

Add 2 new document types to cater for CI Hub and
CI Landing pages, the former with links to the latter.
The CI hub page is now the root document for site.
Replaced invalid double quote characters from Terms and
conditions document content.

[RPS-317] Create CI Hub and landing pages

---

ci-cd/Makefile
cms/src/main/java/uk/nhs/digital/ps/modules/FullTaxonomyModule.java
cms/src/main/java/uk/nhs/digital/ps/modules/searchableFlagModule/DatasetProcessor.java
cms/src/main/java/uk/nhs/digital/ps/modules/searchableFlagModule/PublicationDepublishProcessor.java
cms/src/main/java/uk/nhs/digital/ps/modules/searchableFlagModule/PublicationProcessor.java
cms/src/test/java/org/apache/sling/testing/mock/jcr/MockNode.java
cms/src/test/java/org/apache/sling/testing/mock/jcr/README.md
cms/src/test/java/uk/nhs/digital/ps/modules/searchableFlagModule/DatasetProcessorTest.java
cms/src/test/java/uk/nhs/digital/ps/modules/searchableFlagModule/PublicationProcessorTest.java
pom.xml

Thanks to @mchatzi, who provided us with simple fix to problem, I could
not reproduce the exception anymore.
`JcrUtils.ensureIsCheckedOut(document);` ensure that the node you are
trying to edit is in latest version.
Unfortunatelly I didn't find elegant way to mock `Node#isCheckedOut()`
using jcr-mock package, hence the new `org.apache.slink.testing.mock
.jcr` package was added to the project with modified
`MockNode#isCheckedOut()` method.

[RPS-258] Fix JCR exceptions in HippoEventBus handlers

---

migrator/src/main/java/uk/nhs/digital/ps/migrator/config/MigratorConfiguration.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/Publication.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/GenerateNesstarImportContentTask.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/NesstarImportableItemsFactory.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/CcgImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/CompendiumImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/NhsOutcomesFrameworkImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/SocialCareImportables.java
migrator/src/main/resources/templates/publication.json.ftl
migrator/src/test/java/uk/nhs/digital/ps/migrator/task/NesstarImportableItemsFactoryTest.java

For the clinical indicator import process, information type
is now set to 'Open data' for the publication level content
document.  Also renamed ImportableItemsFactory to
NesstarImportableItemsFactory in order to make it more explicit
that the import is for Nesstar content.

[RPS-324] CI migration set information type

---

cms/src/main/java/uk/nhs/digital/ps/modules/FullTaxonomyModule.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/TaxonomyMigrator.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/report/DatasetMigrationImpact.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/report/IncidentType.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/report/MigrationReport.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/CompendiumImportables.java
repository-data/application/src/main/resources/hcm-config/configuration/update/MigratorImporterScript.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/MigratorImporterScript.yaml

Fixed problem with Taxonomy population during import,
where the FullTaxonomyModule class would obtain an instance
of the Taxonomy document on system start and attempt to use it
during import. When the document was deleted in an early manual
step of the import process, the reference kept by the class would be
no longer valid, causing tagging of documents during import to fail.
The class has been modified to fetch fresh copy of the document
each time it's needed rather that story it as an internal state.
Modified the import script to:
* execute document creation and document publishing in separate
batch units,
* increase gap between execution of batch units from 10ms to
100ms to ensure
This was to ensure that one step is definitely finished before the
other commences as it's been observed …

[RPS-312] Import Initial Content

---

README.md
repository-data/application/src/main/resources/hcm-config/configuration/update/MigratorImporterScript.groovy

Given that we had to fall back to using Hippo's native XML Export/XML Import mechanism to transfer converted CI data between local and remote systems, I have updated Migrator's readme file with more details on how to execute the complete migration process.
Also, fixed one exception string in CompendiumImportable to make it correctly
substitute missing sheet's name in the error message (MessgeFormat ignores '{0}'
and requires pairs of single quotes for correct substitution).

[RPS-308] Better import mechanism

---

migrator/src/main/java/uk/nhs/digital/ps/migrator/report/MigrationReport.java

Info on mapping file used is now included in the migration report's
metadata

[RPS-313] CI Migration: include more fields

---

migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/HippoImportableItem.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/MappedFields.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/model/hippo/Publication.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/NesstarImportableItemsFactory.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/CcgImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/CompendiumImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/NhsOutcomesFrameworkImportables.java
migrator/src/main/java/uk/nhs/digital/ps/migrator/task/importables/SocialCareImportables.java
migrator/src/main/resources/templates/publication.json.ftl
repository-data/application/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/ci-hub.yaml

The nominal date is set on the publications from the
latest date of the child datasets.
Also made the field mapping case insensitive.

[RPS-322] Nominal date for migrated publications

---

acceptance-tests/src/test/resources/features/site/datasets.feature
acceptance-tests/src/test/resources/features/site/facets.feature
acceptance-tests/src/test/resources/features/site/publication.feature
acceptance-tests/src/test/resources/features/site/search.feature
repository-data/application/src/main/resources/hcm-content/content/documents/administration/document-types.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/corporate-website/publication-system.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/facets.ftl
site/src/main/java/uk/nhs/digital/common/components/FacetComponent.java

Made them use the configurable doc type labels.
Also fixed a bug where taxonomy terms would repeat if the
taxonomy key was invalid.

[RPS-350] Made Doc type facets consistent

---

Makefile
cms/pom.xml
conf/log4j2-dev.xml
pom.xml

Update config to allow passing in of Splunk HTTP Event
Collector (HEC) name which feeds the Source in the
log4j Appenders configuration. The Splunk instance will
have a HEC setup for each environment, making it easy to
filter events in queries (i.e only show PROD or TEST events)

[RPS-381] Create Splunk HEC for each environment

---

repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/indicator.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/sample-indicator.yaml
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl
site/src/main/java/uk/nhs/digital/nil/beans/Indicator.java

Evolution of the NIL Indicator document type - split the field 'descriptor' into four fields - 'data source', 'numerator', 'denominator' and 'calculation'. Updated the seeded sample indicator.
Migration project will be updated next.

[NIL] Split 'descriptor' field into four new fields

---

repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/indicator.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/sample-indicator.yaml
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl

Remove 'published date' from the NIL Indicator document type. Business decision made - this was causing confusion with the 'assured date' and is not required. Migrator will be updated separately.

[NIL] Remove Published Date from Indicator doc type

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/util/TestContentUrls.java
acceptance-tests/src/test/resources/features/site/datasets.feature
acceptance-tests/src/test/resources/features/site/publication.feature
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/coveragedates-test.yaml
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/dataset.ftl
site/src/main/java/uk/nhs/digital/ps/directives/CoverageDatesFormatterDirective.java

Update coverage dates and next publication date (datasets) to be
consistent with publication date. Format should be dd MMM yyyy

[RPS-384] Consistent date formats on publication/dataset page

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/cms/ps/CmsSteps.java
repository-data/application/src/main/resources/hcm-config/configuration/domains/statistical-publications-and-clinical-indicators-read.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/another-upcoming-publication.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/fusce-viverra-dolor.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/lorem-ipsum.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/morbi-tempor-euismod-vehicula.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/morbi-vitae-nunc-ac-lacus-malesuada-tempus.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/nullam-vel-ligula-dapibus.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/nunc-tempus-ante-nec.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/proin-elementum-justo-eu-tortor.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/lorem-ipsum-content/proin-nec-justo.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/search-test-loremipsumdolor/loremimsumdolor.yaml

Fix bug whereby for non-admin users, validation didnt fire upon
leaving a blank attachment field or when uploading file types
which are prohibited.
Also corrected issue with test data coverage start and end date times,
which are now defaulted to midnight since user cannot select time.

[RPS-387] Fix attachment validation for non-admin users

---

repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/indicator.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/sample-indicator.yaml

Update the Indicator document type to be classifiable. No impact on searching yet - that will be a later PR.

[NIL-108] Add taxonomy to the NIL Indicator document type

---

repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary.cnd
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/actionlink.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/nihublink.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/nilanding.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library/headers.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/add.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/advice.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/apply.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/nihub.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/sample-indicator.yaml
repository-data/development/src/main/script/YamlFormatter.groovy
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/nihub.ftl
repository-data/webfiles/src/main/resources/site/less/style.less
site/src/main/java/uk/nhs/digital/nil/beans/ActionLink.java
site/src/main/java/uk/nhs/digital/nil/beans/NiHub.java
site/src/main/java/uk/nhs/digital/nil/beans/NiHubLink.java
site/src/main/java/uk/nhs/digital/nil/beans/NiLanding.java

This change comprises of:
1) NIL "hub links" and landing pages doc types. The test instances of these are just skeletal.
2) New "action link" compound - this is to allow the configuration of multiple links within the NI hub. Similar to related link but without the protocol validation.
3) Changes to the NI hub template to support the above. The test content is a work in progress to match the evolving prototype - there will have to be a further iteration of this along with an acceptance test feature when that is signed off.
NB, I've added a few styles in to the main .less file. I'm not 100% sure where this should go.

[NIL-96] NIL landing page content

---

acceptance-tests/pom.xml
conf/maven-version-rules.xml
pom.xml

Added a plugin that will enforce that the version of a dependency used
in our project is at least the version specified by any of the
transitive dependancies.
Also fixed some of the errors and added a few more useful enforcer
rules.

[RPS-377] Fix maven transitive dependencies

---

repository-data/webfiles/src/main/resources/site/freemarker/common/base-layout.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/cilanding.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/dataset.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/legacy-publication.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl

Added Google Analytics tracking events (using gtag) for download clicks
and external link clicks.  Events are displayed will in Google Analytics
dashboard under 'Behaviour > Events' or 'Real Time > Events' and grouped
into Category, Action and Label.

[RPS-391] Add Google analytics download and external link tracking

---

repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library/headers.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/sample-indicator.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/results.ftl
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl

Alters layout for assurance date and publisher in results macro.
Adds 'Assured' to nationalindicatorlibrary:headers.
Doesn't show description as that is in NIL-119
Displayed assurance status on indicator summary page and search results
is now conditional on assurance

[NIL-99] Adds more details to indicator search results

---

repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/indicator.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library/headers.yaml
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl
site/src/main/java/uk/nhs/digital/nil/beans/Indicator.java

Basic addition of resources to the Indicator document type. No further requirements at this stage hence the existing plugin is sufficient.

[NIL-98] Add resources to Indicator document type

---

.travis.yml
Makefile
acceptance-tests/pom.xml
ci-cd/Makefile
cms/src/main/java/uk/nhs/digital/ps/modules/AbstractDaemonModule.java
cms/src/main/java/uk/nhs/digital/ps/modules/FullTaxonomyModule.java
essentials/pom.xml
pom.xml
repository-data/application/src/main/resources/hcm-config/configuration/update/HotFixSearchableAndFullTaxonomy.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/HotFixSearchableAndFullTaxonomy.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/website/general-type.yaml

This is a bit dirty, but:
* Content migrator package is the same as the "Taxonomy" daemon package.
* Private class "TaxonomyDaemonCopy" extends "FullTaxonomyModule" in
order to do stay in sync with the current implementation.
* Minimal change to "AbstractDaemonModule" to allow injection of the
JCR session object.

[RPS-394] HotFix for missing hidden fields

---

acceptance-tests/src/test/resources/features/site/facets.feature
conf/query/lucene/indexing_configuration.xml
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/details.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/indicator.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/topbar.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/facet-headers.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library/headers.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/corporate-website/facet.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/acceptance-tests/bare-minimum-indicator.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/acceptance-tests/unassured-indicator.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/sample-indicator.yaml
repository-data/development/src/main/resources/hcm-content/content/taxonomies/publication_taxonomy.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/facets.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/results.ftl
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl
site/src/main/java/uk/nhs/digital/nil/beans/Indicator.java
site/src/main/java/uk/nhs/digital/nil/beans/Topbar.java

Addition of 3 new facets which relate to the NIL Indicator document type.
Most of the "noise" here is the moving of 4 searchable fields and taxonomy/classifiable out of the Topbar component and into the main Indicator document. This is required because Lucene requires a flat data-model.
Also added geographical location to Indicator and cleaned up the Indicator.ftl.
(Note, there is no migration script as there is no content to migrate at this point. Also the hippo migration project will be updated separately.)

[NIL-90] NIL search facets and supporting changes

---

repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library/headers.yaml
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl
site/src/main/java/uk/nhs/digital/nil/beans/Indicator.java

Simple display of taxonomy 'categories' on the NIL Indicator summary page - as per the prototype.

[NIL-122] Display tagged taxonomy on Indicator summary

---

conf/maven-version-rules.xml
pom.xml

Preview doesn't work with the latest version of `com.fasterxml.jackson.core` so I've stuck to the version that works.

[RPS-423] Fix for broken preview

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/site/SearchSteps.java
acceptance-tests/src/test/resources/features/site/search.feature
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/indicator.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/topbar.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library/headers.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library/labels.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/acceptance-tests/national-indicator.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/acceptance-tests/search-test-definition-indicator.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/acceptance-tests/search-test-title-indicator.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/acceptance-tests/unassured-indicator.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/sample-indicator.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/results.ftl
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl
site/src/main/java/uk/nhs/digital/common/components/SearchComponent.java
site/src/main/java/uk/nhs/digital/nil/beans/Indicator.java
site/src/main/java/uk/nhs/digital/nil/beans/Topbar.java

Move the assurance date field out of the "Topbar" component and into the main Indicator document. This is required for sorting which has to be top-level.
Also includes a couple of minor template fixes.
Note, I've kept the acceptance tests separate for NIL to keep them simple.
(I'm not migrating existing content as NIL content is still in a state of flux and will be wiped and re-imported. HOWEVER post approval please let me merge this).

[NIL-91] Move assurance date and include in sort

---

repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl
repository-data/webfiles/src/main/resources/site/less/style.less
site/src/main/java/uk/nhs/digital/nil/beans/Indicator.java
site/src/main/java/uk/nhs/digital/ps/beans/HippoBeanHelper.java

The NIL Indicators already have their 'tagged' taxonomies displayed. This addresses the requirement to make them clickable - i.e. direct to a search for that term.
(Note, I will be adding more acceptance tests under a separate PR)

[NIL-127] Display taxonomy tags on Indicator as clickable

---

cms/pom.xml
cms/src/main/java/uk/nhs/digital/externalstorage/modules/S3ConnectorServiceRegistrationModule.java
cms/src/main/java/uk/nhs/digital/externalstorage/resource/ImageDisplayPlugin.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/AbstractExternalFileTask.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFilePublish/ExternalFilePublishAction.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFilePublish/ExternalFilePublishTask.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFileUnpublish/ExternalFileUnpublishAction.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFileUnpublish/ExternalFileUnpublishTask.java
cms/src/test/java/uk/nhs/digital/externalstorage/s3/S3ConnectorImplTest.java
cms/src/test/java/uk/nhs/digital/externalstorage/workflow/externalFilePublish/ExternalFilePublishTaskTest.java
cms/src/test/java/uk/nhs/digital/externalstorage/workflow/externalFileUnpublish/ExternalFileUnpublishTaskTest.java
repository-data/application/src/main/resources/hcm-config/configuration/modules/documentworkflow.scxml
repository-data/application/src/main/resources/hcm-config/configuration/modules/s3ConnectorRegistrationModule.yaml
repository-data/application/src/main/resources/hcm-config/configuration/modules/scxmlregistry.yaml

Two simple actions to add or remove public ACL on S3 objects embedded in
the workflow document.
This version does no handle S3 errors yet.

[RPS-419] Add S3 publish and unpublish scxml action

---

repository-data/application/src/main/resources/hcm-config/hst/configurations/common/sitemap.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/nihub.yaml

[NIL-146] Moves nihub.yaml to application and adds nihub to methodologies root on the sitemap

NIL-146 Adds Nihub to methodologies root

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/util/TestContentUrls.java
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/sitemap.yaml

Changes URL for 'methodologies' to 'national-indicator-library'

[NIL-144] URL change for NIL

---

repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl

[NIL-147] Makes 'Interpretation Guidelines' and 'Caveats' headings' appearance conditional on their having content. In the details section of indicator summary page.

Makes headings conditional on them having content

---

acceptance-tests/src/test/resources/features/site/search.feature
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/pages/search.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/templates.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/feature-toggles.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/searchtab-labels.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/base-layout.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/searchTabsComponent.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/searchresults.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/searchtabs.ftl
repository-data/webfiles/src/main/resources/site/less/style.less
site/src/main/java/uk/nhs/digital/common/components/SearchComponent.java
site/src/main/java/uk/nhs/digital/common/components/SearchTabsComponent.java
site/src/main/java/uk/nhs/digital/common/enums/SearchArea.java

This is ready for formal review now.
This PR provides tabbed search using 'scope' to determine which content will be surfaced. Scope derivation is now more elegant than the first iteration.
Tab structure/style follows the Gov site as has been agreed.
Note as there is no (as yet) 'services' or 'news' content, the acceptance test asserts this.

NIL 129 tabbed search

---

repository-data/application/src/main/resources/hcm-config/hst/configurations/common/pages/search.yaml

Suppress the waste warning - this is occurring when the search tabs feature is toggled off but we know this is temporary.

[NIL-151] Suppress search tabs waste warning

---

repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/nihub.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/nihub.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/national-indicator-library/help.yaml
repository-data/development/src/main/script/YamlFormatter.groovy
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/nihub.ftl
repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/nilanding.ftl
repository-data/webfiles/src/main/resources/site/less/style.less

Comprises of some minor rework of NIL static content to reflect the latest UAT review. 
Also as sorting exclusion list for YAML formatter. (otherwise, without changing the sort behaviour to handle alpha-num, sequences of > 9 are sorted with ill-effects).

[NIL-149] NIL static content tweaking and YAML formatter sorting

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/data/ExpectedTestDataProvider.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/models/section/RelatedLinkSection.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/site/ps/PublicationPage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/widgets/RelatedLinkSectionWidget.java
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/publication.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/sectioned-publication.yaml
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/macro/sections/related-linkSection.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/macro/sections/sections.ftl
site/src/main/java/uk/nhs/digital/ps/beans/RelatedLink.java

Repeating Body section of publication now includes another option
to add a Related Link (alongside image and text).

[RPS-446] Add related link component to repeating body section

---

repository-data/webfiles/src/main/resources/site/freemarker/nationalindicatorlibrary/indicator.ftl

This was missed in the recent "geographical coverage" changes. Fix to Indicator template.

[NIL-152] Fix geographical coverage display

---

acceptance-tests/src/test/resources/features/site/nationalIndicatorsHub.feature
repository-data/application/src/main/resources/hcm-content/content/documents/administration/national-indicator-library/headers.yaml

Header has been updated manually in the CMS. However this keeps it in sync.

[NIL-158] Correct find-out-more heading

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/util/TestContentUrls.java
acceptance-tests/src/test/resources/features/site/clinicalIndicatorsHub.feature
cms/src/main/java/uk/nhs/digital/externalstorage/ExternalStorageConstants.java
cms/src/main/java/uk/nhs/digital/externalstorage/modules/S3ConnectorServiceRegistrationModule.java
cms/src/main/java/uk/nhs/digital/externalstorage/modules/S3ConnectorServiceRegistrationModuleParams.java
cms/src/main/java/uk/nhs/digital/externalstorage/resource/ImageDisplayPlugin.java
cms/src/main/java/uk/nhs/digital/externalstorage/resource/ResourceUploadPlugin.java
cms/src/main/java/uk/nhs/digital/externalstorage/s3/BlockingPooledS3Connector.java
cms/src/main/java/uk/nhs/digital/externalstorage/s3/S3ObjectKeyGenerator.java
cms/src/main/java/uk/nhs/digital/externalstorage/s3/S3SdkConnector.java
cms/src/test/java/uk/nhs/digital/externalstorage/s3/BlockingPooledS3ConnectorTest.java
cms/src/test/java/uk/nhs/digital/externalstorage/s3/S3ObjectKeyGeneratorTest.java
cms/src/test/java/uk/nhs/digital/externalstorage/s3/S3SdkConnectorTest.java
repository-data/application/src/main/resources/hcm-config/configuration/modules/s3ConnectorRegistrationModule.yaml
s3connector/src/main/java/uk/nhs/digital/externalstorage/s3/S3Connector.java
s3connector/src/main/java/uk/nhs/digital/externalstorage/s3/SchedulingS3Connector.java
site/src/main/java/uk/nhs/digital/common/valve/S3ConnectorValve.java
site/src/main/resources/META-INF/hst-assembly/overrides/s3ConnectorPipeline.xml
site/src/test/java/uk/nhs/digital/common/valve/S3ConnectorValveTest.java

It is now possible to configure limit of how many concurrent uploads and
downloads to and from S3 can be served concurrently.
Both can be configured via a Console/JCR properties, where the number of
uploads is being controlled separately from tghe number of downloads.
Changes to configuration in JCR are picked up immediately as they are
committed.
The same values can also be set via JVM system properties/command line;
these take precedence over values configured in JCR which may come handy
in development/testing scenarios.
See S3ConnectorServiceRegistrationModuleParams for applicable settings'
keys.

[RPS-450] RPS-450 cap S3 concurrent uploads

---

site/src/main/java/uk/nhs/digital/common/ServiceProvider.java
site/src/main/java/uk/nhs/digital/externalstorage/s3/valves/S3ConnectorValve.java
site/src/main/resources/META-INF/hst-assembly/overrides/s3ConnectorPipeline.xml
site/src/test/java/uk/nhs/digital/externalstorage/s3/valves/S3ConnectorValveTest.java

Configuration of SchedulingS3Connector service can be changed via
Console on the fly, without restarting the server. This stops the thread
pools from accepting new tasks, un-registers the previous instance of
the service, initialises new thread pools and registers new instance
of the service.
S3ConnectorValve used to only retrieve an instance of this service once,
upon system start and would not use the latest instance of the service,
which would lead to the stopped thread pools reject download requests,
breaking the Channel Manager Preview in the process.
This fix eliminates this problem by making the valve retrieve the latest
instance of the service for each download request rather than get it
once and store as a field for the lifetime of the valve object.

RPS-450 cap S3 concurrent uploads

---

site/src/main/java/uk/nhs/digital/common/components/SearchComponent.java

It appears that when the 'timeframe' facet is specified last
in the search URL and its value is the only one in the query that makes
it not match any documents, the resultSet returned from the
facetNavigationBean is null rather than empty. The null value was the
source of the offending exception seen in the logs.
There is now a null-check in place to prevent the exception from being
thrown.

[RPS-487] NPE in SearchTabsComponent

---

repository-data/application/src/main/resources/hcm-config/configuration/frontend/cms.yaml

Configuration of ImageValidationService has been updated to prevent
uploads of image files with extension 'svg', regardless of whether they
contain a script or not.

[RPS-480] Restrict SVG upload to Hippo CMS

---

acceptance-tests/.gitignore
ci-cd/Makefile
cms/src/main/java/uk/nhs/digital/JcrQueryHelper.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/AbstractExternalFileTask.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFilePublish/ExternalFilePublishTask.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFileUnpublish/ExternalFileUnpublishTask.java
cms/src/main/java/uk/nhs/digital/ps/PublicationSystemConstants.java
cms/src/main/java/uk/nhs/digital/ps/workflow/searchableFlag/SearchableFlagTask.java
cms/src/test/java/uk/nhs/digital/externalstorage/workflow/externalFilePublish/ExternalFilePublishTaskTest.java
cms/src/test/java/uk/nhs/digital/externalstorage/workflow/externalFileUnpublish/ExternalFileUnpublishTaskTest.java
docs/what-if/deploy-to-test.md

This change adds checks for publish and un-publish workflow tasks to
ensure that when:
* Publishing a data set document, we will only make its attachments
public if its parent publication is "finalised".
* Publishing publication document, we will make its attachments public
if it is "finalised". We will also find all data set documents
belonging to that publication and make its attachments public.
* Publishing publication document we will make its attachments private
if it is "upcoming". We will also find all data set documents
belonging to that publication and make its attachments private.
* Un-publishing publication document, we will make its attachments
private. We will also find all data set documents belonging to that
publication and meke its attachments private.

[RPS-461] Publish only finalised publication resources

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/models/GeographicCoverage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/ContentPage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/widgets/GeographicCoverageCmsWidget.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/cms/ps/CmsSteps.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/util/TestContentUrls.java
acceptance-tests/src/test/resources/features/cms/createAndPublish.feature
acceptance-tests/src/test/resources/features/cms/datasetValidation.feature
acceptance-tests/src/test/resources/features/cms/publicationValidation.feature
acceptance-tests/src/test/resources/features/cms/userGroups.feature
acceptance-tests/src/test/resources/features/site/datasets.feature
acceptance-tests/src/test/resources/features/site/facets.feature
acceptance-tests/src/test/resources/features/site/publication.feature
repository-data/application/src/main/resources/hcm-config/configuration/domains/cms-user-read.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/nationalindicatorlibrary/indicator.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/dataset.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/legacypublication.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/publication.yaml
repository-data/application/src/main/resources/hcm-content/content/documents/administration/value-lists.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/facets-test.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/geographic-coverage-test.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/acceptance-tests/series-with-publication-with-datasets/series-publication-with-datasets/series-publication-with-datasets-dataset.yaml
site/src/main/java/uk/nhs/digital/common/enums/Region.java
site/src/main/java/uk/nhs/digital/nil/beans/Indicator.java
site/src/main/java/uk/nhs/digital/ps/beans/BaseDocument.java
site/src/main/java/uk/nhs/digital/ps/beans/Dataset.java
site/src/main/java/uk/nhs/digital/ps/beans/PublicationBase.java

Replaced Geographic Coverage picker with five check boxes, as follows:
England,Wales,Scotland,Northern Ireland,Republic of Ireland
Also serve up the following to the front-end
* If England,Wales,Scotland are checked and no others - Great Britain
* If England,Wales,Scotland and Northern Ireland are checked and no
others - United Kingdom
* If England,Wales,Scotland,Northern Ireland and Republic of Ireland
are checked - British Isles
* If any other combination is checked, serve up list of checked values
Note: Check boxes are optional (i.e. all can be unchecked). Script to update existing values is not required since no values for Great Britain,UK or International exist in RPS content, and CW have not migrated yet and will map to new values. This change exposes the Administration folder as …

[RPS-456] Update Geographic Coverage as par DW-178

---

repository-data/application/src/main/resources/hcm-config/configuration/update/Migration20180502RevertExternalAttachmentsToEmbedded.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/Migration20180502RevertExternalAttachmentsToEmbedded.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem.cnd

You can't add mixin types to already defined node definitions as you get
errors when deploying to onDemand. I have updated the rollback
script to add the required mixin if the error occurs instead
of in the node definition.

[RPS-451] Changed the s3 rollback script

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/util/TestContentUrls.java
acceptance-tests/src/test/resources/features/site/ciBreadcrumb.feature
repository-data/application/src/main/resources/hcm-config/hst/configurations/base/components/breadcrumb-ci-old-styling.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/base/components/breadcrumb-ci.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/base/templates.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/abstractpages/basepage.yaml
repository-data/application/src/main/resources/hcm-config/hst/configurations/common/abstractpages/pubs_apppage.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/publicationsystem/cilanding.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/ci-hub.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/clinical-indicators.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/base-layout.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/breadcrumb-ci-old-styling.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/breadcrumb-ci.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/pubs_app-layout.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/cilanding.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/legacy-publication.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/series.ftl
site/src/main/java/uk/nhs/digital/ps/beans/CiLanding.java
site/src/main/java/uk/nhs/digital/ps/beans/navigation/CiBreadcrumb.java
site/src/main/java/uk/nhs/digital/ps/beans/navigation/CiBreadcrumbProvider.java
site/src/main/java/uk/nhs/digital/ps/components/CiBreadcrumbComponent.java

Added breadcrumbs for CI content (series,publication,
datasets). If the document sits under one of the
clinical indicator folders (i.e. CCG, SHMI), then a
breadcrumb back to that CI landing page is also added
to the hierarchy.
Note: 2 separate breadcrumbs had to be created, one
which uses the old styling (breadcrumb-ci-old-styling)
and one which uses the new styling (breadcrumb-ci). Once
the dataset template has been updated with the new styling,
then breadcrumb-ci-old-styling can be removed, and replaced
with the same breadcrumb that the publication/series page
uses.

[RPS-365] Create breadcrumbs for CI pages

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/util/TestContentUrls.java
acceptance-tests/src/test/resources/features/site/ciBreadcrumb.feature
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/publication-system/clinical-indicators.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/breadcrumb-ci-old-styling.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/breadcrumb-ci.ftl
site/src/main/java/uk/nhs/digital/ps/beans/navigation/CiBreadcrumbProvider.java

Also adds some logic which will reduce the noise in Splunk logs,in
particular from the Page Not found template which uses base-layout
(which references the breadcrumb-ci-old-styling template)

[RPS-512] Fix breadcrumb for achived publicaton document type

---

Makefile
cms/src/main/java/uk/nhs/digital/externalstorage/modules/S3ConnectorServiceRegistrationModule.java
cms/src/main/java/uk/nhs/digital/externalstorage/modules/S3ConnectorServiceRegistrationModuleParams.java
repository-data/application/src/main/resources/hcm-config/configuration/modules/s3ConnectorRegistrationModule.yaml
repository-data/development/src/main/resources/hcm-config/configuration/modules/s3ConnectorRegistrationModule.yaml

S3 Connector config updated to make it clearer which settings are
set by system properties and which are set via JCR.
The following are now set as system properties only, since the
likelyhood of wanting to change these on the fly (via JCR) is very
unlikely, and potentially risky:
external.aws.bucket
external.aws.region
external.aws.s3.endpoint
The following are set via JCR. These values can be modified
on the fly in the console, but because they are part of
the bootstrapped config, any updated values are not persisted
opon a new release. To update the values permanently, update
the values in s3ConnectorRegistrationModule.yaml:
maxConcurrentDownloadsCount
downloadShutdownTimeoutInSecs
maxConcurrentUploadsCount
uploadShutdownTimeoutInSecs

[RPS-475] Improve S3 connector config mechanism

---

Makefile
cms/src/main/java/uk/nhs/digital/externalstorage/modules/S3ConnectorServiceRegistrationModule.java
pom.xml

Instead of System variables, use Environment variables for
S3 AWS accessKeyId and secretKey which prevents the credentials
being visible in the catalina logs, and on the Admin System
Properties CMS screen.

[RPS-491] S3 use environment variables

---

cms/src/main/java/uk/nhs/digital/externalstorage/ExternalStorageConstants.java
cms/src/main/java/uk/nhs/digital/externalstorage/s3/BlockingPooledS3Connector.java
cms/src/main/java/uk/nhs/digital/externalstorage/s3/S3SdkConnector.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/AbstractExternalFileTask.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFileCopy/ExternalFileCopyAction.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFileCopy/ExternalFileCopyTask.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFilePublish/ExternalFilePublishTask.java
cms/src/main/java/uk/nhs/digital/externalstorage/workflow/externalFileUnpublish/ExternalFileUnpublishTask.java
cms/src/test/java/uk/nhs/digital/externalstorage/s3/BlockingPooledS3ConnectorTest.java
cms/src/test/java/uk/nhs/digital/externalstorage/s3/S3SdkConnectorTest.java
cms/src/test/java/uk/nhs/digital/externalstorage/workflow/externalFileCopy/ExternalFileCopyTaskTest.java
repository-data/application/src/main/resources/hcm-config/configuration/modules/documentworkflow.scxml
repository-data/application/src/main/resources/hcm-config/configuration/modules/scxmlregistry.yaml
s3connector/src/main/java/uk/nhs/digital/externalstorage/s3/PooledS3Connector.java
s3connector/src/main/java/uk/nhs/digital/externalstorage/s3/S3Connector.java

From now on, making a copy of a document also creates fresh copies of
the document's files hosted in S3.

[RPS-499] copy S3 attachments with doc

---

cms/src/main/java/uk/nhs/digital/externalstorage/s3/S3TransfersReportingTracker.java
repository-data/application/src/main/resources/hcm-config/configuration/modules/s3ConnectorRegistrationModule.yaml

Concurrently modified counters are now designated 'volatile' to prevent
the risk that different threads getting different values of the fields
in the shared instance.
Also, caps on the maximum numbers of concurrent downloads and uploads
via CMS have now been set to values concluded in the S3 integration
performance test.

[RPS-497] RPS-450 S3 logs fix and upload cap values

---

repository-data/application/src/main/resources/hcm-config/configuration/update/DW-366-GdprUpdateWhoCanAccessField.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/DW-366-GdprUpdateWhoCanAccessField.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/website/gdprtransparency.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/gdpr-article.ftl
site/src/main/java/uk/nhs/digital/website/beans/Gdprtransparency.java

Update GDPR Transparency document type to change the 'who can
access' field from a String field to a Rich Text field. Add groovy
script which copies values over from old field to new field.

[DW-366] GDPR transparency update who can access field

---

cms/src/main/java/uk/nhs/digital/repository/schedulers/ConditionalFormDataCleanupJob.java
conf/query/lucene/indexing_configuration.xml
repository-data/application/src/main/resources/hcm-config/configuration/modules/scheduler.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/website/componentlist.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/alphabeticalGroupOfGDPRDocuments.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/hubBox.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/hubPageComponents.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/results.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/site-footer.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/macro/publicationHeader.ftl
repository-data/webfiles/src/main/resources/site/freemarker/publicationsystem/publication.ftl
site/src/main/java/uk/nhs/digital/common/components/SearchComponent.java

Add ComponentList doc type to search results, and other fixes which
include:
DW-491 Fix spelling of LinkedIn on image Alt text in footer
DW-453 Anchor links not working on certain pages
DW-495 Remove H3 Doctype indicators in search
DW-496 Closing unopened ul tag
DW-416 UI - A-Z navigation broken on GDPR summary page
DW-504 Fix sticky nav on publications with pages
DW-302 Fix forms cleanup job

[DW-490] Add Links list to search results and other UI updates

---

repository-data/application/src/main/resources/hcm-config/configuration/update/DW-489-gdpr-results-too-high-in-search-results.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/DW-489-gdpr-results-too-high-in-search-results.yaml
repository-data/application/src/main/resources/hcm-config/configuration/update/DW-510-update-links-list-doc-type-search-rank.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/DW-510-update-links-list-doc-type-search-rank.yaml

Add groovy script to reduce common:searchRank property of
GDPR transparency documents from 5 to 2 as these were incorrectly
set on mass import. The GDPR transparency document type is already
correctly set to 2.
DW-510 script to update old Links List doc types to include
search rank property

[DW-489] DW-510 Reduce GDPR searchRank and update old LinkList docs

---

repository-data/webfiles/src/main/resources/site/freemarker/common/event-article.ftl

Remove H4 tags which are causing accessibility problems, but
maintain visual formatting

[DW-516] Update session titles in event doctype

---

site/src/main/java/uk/nhs/digital/common/contentrewriters/GoogleAnalyticsContentRewriter.java
site/src/test/java/uk/nhs/digital/common/contentrewriters/GoogleAnalyticsContentRewriterTest.java

OnKeyUp attribute was added to links as part of DW-290, but
were not applied to links within Rich Text Editor content. Update
the GoogleAnalyticsRewriter to include the snippet:
onKeyUp="return vjsu.onKeyUp(event)" which should improve
accessibility of links.

[DW-520] Add equivalent handler for onclick

---

repository-data/application/src/main/resources/hcm-config/configuration/update/DW-557-remove-migration-broken-link.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/DW-557-remove-migration-broken-link.yaml

Remove instances of the following URL, which was created from
the migration:
http://www.hscic.gov.uk/article/1165/Search-catalogue?q=title:

[DW-557] Script to remove old migration link

---

cms/pom.xml

This is required to enable packaged distribution uploads to
the new BloomReach Cloud

[DW-693] Add Lucene index export service to project

---

repository-data/webfiles/src/main/resources/site/freemarker/common/event-article.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/list-article/unordered-list-article.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/childPageGrid.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/furtherInformationSection.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/published-work-article.ftl

@GeoffHayward @ngta1 
Can you take a look at this one? The block link style has been applied to the remaining templates and styling amended. In terms of the story I am done. I think there needs to be a tidy up ticket as a follow up to this one. At the moment the block links are all output in lists. Each item is counted as part of the list even when it sits outside of the specific list.

[DW-737] Adds download styling to more doctypes

---

cms/src/main/resources/ckeditor/plugins/table/dialogs/table.js
repository-data/application/src/main/resources/hcm-config/configuration/modules/htmlprocessor.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/hippostd/html.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/website/emphasisbox.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/website/glossaryitem.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/website/section.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/scripts/init-table-sort.js.ftl

Checkbox option added to CKeditor Table component to suppress
table sorting (which is enabled by default). Note: implementation
involves duplicating and modifying the file:
table > dialogs > table.js
Therefore, as with all CMS customisations, there is
a risk when upgrading the Hippo version of this
functionality breaking (CKEditor table or CKEditor in general)

[DW-751] Add option to suppress table sorting

---

acceptance-tests/pom.xml
buildspec.yml

Change buildspec to use OpenJDK instead of Oracle JDK given the
changes to the Oracle JDK License for releases starting April 16, 2019.
Also update Chromedriver download to use hardcoded URL since the latest
version (currently 74) is no longer referenced in repository-3.0.json

[DW-831] Update buildspec Java and acceptance test Chromedriver

---

repository-data/webfiles/src/main/resources/site/freemarker/common/glossary-list.ftl

Remove `<div>` tags under `<dt>` elements.  Although the official W3C validator allows it, Sitemorse validator doesnt.

[DW-830] Update Glossary dt div tags

---

repository-data/webfiles/src/main/resources/site/freemarker/common/macro/component/pagination.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/published-work-article.ftl
site/src/main/java/uk/nhs/digital/website/beans/Publishedworkchapter.java

- Publishedworkchapter now use title for equality checking
- published-work-article now includes the first page in chapter list
- published-work-article has erroneous var removed from hst.link
- Moves the opening HTML UL element inline with an if block

[DW-876] Fixes bugs in Published Works

---

pom.xml
repository-data/application/src/main/resources/hcm-config/targeting.yaml

The core product defines 4 characteristics which have
".meta:residual-child-node-category: content" set,
and treats newly added target groups as "Content".
More characteristics have since been added by BloomReach,
but they forgot to update the core config to include
".meta:residual-child-node-category: content"
with the new characteristics.  Therefore added in targeting.yaml
to ensure they are bootstrapped in.
Also includes security update to fasterxml jackson libs

[DW-1020] Ensure relevance characteristics persist

---

.dependabot/config.yml

Now that GitHub will make auto PR to Maven dependencies that are
know to have security issues, the commit message must conform.

[DW-000] Adds a Dependabot config

---

vars.mk

It seems AWS CodeBuild does a shallow clone and the buildnumber-maven-plugin
breaks.

[DW-000] Feeds CODEBUILD_SOURCE_VERSION to -DbuildNumber

---

.git-local/hooks/commit-msg

The commit message hook was not compatible with Python 3
This was due to the deprecated print statement syntax
This has been replaced with a Python 3 compatible
syntax, that should still work in Python 2.

[DW-0000] Python 3 compatible commit hook

---

repository-data/application/src/main/resources/hcm-config/namespaces/website/navigation.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/website/statistics.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/sections/navigation.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/macro/sections/statistics.ftl

The option values for the Navigation and Statistics items were not conforming to the expected values.
They were failing this test: https://github.com/NHS-digital-website/hippo/blob/5ae59525ed599465dbf4b4d03508c1f29fe894db/site/components/src/main/java/uk/nhs/digital/indices/StickySection.java#L26

[DW-0000] Navigation & Statistics in sticky nav

---

repository-data/webfiles/src/main/resources/site/scss/components/_hero-module-header.scss

- Fix image warping at tablet size
Screenshots at iPad portrait size of 768x1024:
Before:
After:

[DW-1425] Published Work hero image

---

repository-data/webfiles/src/main/resources/site/scss/components/_navigation-tiles.scss

This is specifically to override the
`.article-section * + *` selector.
Before:
After:

[DW-1458] Make sure navigation tiles have equal spacing

---

repository-data/webfiles/src/main/resources/site/freemarker/common/cyber-alert-article.ftl

- Revert accidental change made in revision ab6872fc33b6ae7b7538bfe073d2dca447bc6bd5
Before:
After:

[DW-000] Fix cyber alert columns

---

cms/src/main/resources/ckeditor/extraConfiguration.js
repository-data/application/src/main/resources/hcm-config/namespaces/website/financial.yaml

The deleted section that starts `/hipposysedit:nodetype[2]:` was a CMS 'uncommited' change that had been committed to git. The doctype's config is now clean.

[DW-1554] Allows merge cell on financial doctype

---

cms/src/main/resources/api-specification/codegen-templates/index.mustache
cms/src/main/resources/api-specification/codegen-templates/param.mustache
cms/src/test/resources/test-data/api-specifications/ApiSpecConversionJobIntegrationTest/customised-codegen-v3-generated-spec.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenApiSpecHtmlProviderTest/customised-codegen-v3-generated-spec.html

In API Specifications, default values are now being
displayed for those request parameters that have
them defined.
Also, a few headers were improved.

[ADZ-423] Display default request param value

---

cms/src/main/java/uk/nhs/digital/apispecs/swagger/ApiSpecificationStaticHtml2Codegen.java
cms/src/main/resources/api-specification/codegen-templates/body_param.mustache
cms/src/test/resources/test-data/api-specifications/ApiSpecSyncFromApigeeJobIntegrationTest/customised-codegen-v3-generated-spec.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/customised-codegen-v3-generated-spec.html
repository-data/webfiles/src/main/resources/site/freemarker/common/api-try-it-now.ftl
repository-data/webfiles/src/main/resources/site/src/scss/components/_apispecification.scss

Also implements ADZ-499 'Point Developers to Try This API to see field descriptions'.
Temporary change to be reverted once the payload schemas are exposed in the main spec page.

[ADZ-497] Field description in Try this API

---

repository-data/application/src/main/resources/hcm-config/configuration/update/DW-1806-remove-wide-mode-property.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/DW-1806-remove-wide-mode-property.yaml
repository-data/application/src/main/resources/hcm-config/configuration/update/DW-1806-set-narrow-view-as-default.groovy
repository-data/application/src/main/resources/hcm-config/configuration/update/DW-1806-set-narrow-view-as-default.yaml
repository-data/application/src/main/resources/hcm-config/namespaces/website/general.yaml
repository-data/development/src/main/resources/hcm-content/content/documents/corporate-website/general.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/general-article.ftl
repository-data/webfiles/src/main/resources/site/freemarker/common/service/service-article.ftl
site/components/src/main/java/uk/nhs/digital/website/beans/General.java

- A script to add 'website:navigationcontroller' with a default to
all general doctype entries.
- A script to remove 'website:wideMode' from all general doctype
entries. If it was set to true then 'website:navigationcontroller'
gets set accordingly.
- Removes the config for 'website:wideMode'.

[DW-1806] Adds widemode/narrow view groovy scripts

---

repository-data/site/src/main/resources/hcm-config/hst/configurations/common/pages/news-hub.yaml

The news hub page was using the Cyber Security page's banner and main
content containers. This led to some content clashing between the two.

[DW-0000] Fix channel manager content clash

---

.github/workflows/master-to-uat-workflow.yml
.github/workflows/slack-deploy-command.yml

And tidies up
- Moves RD env var's out of shared scope
- Switches master-to-uat-workflow.yml to RD_API over RD_URL
- Removes the deployment-testing channel as that was just needed during early development

[DW-1529] Fix Slack user_name to user_id

---

acceptance-tests/pom.xml
cms/pom.xml
cms/src/main/java/uk/nhs/digital/apispecs/exception/ApiCatalogueException.java
cms/src/main/java/uk/nhs/digital/apispecs/exception/ApiCatalogueJobException.java
cms/src/main/java/uk/nhs/digital/apispecs/module/ApiSpecSyncFromApigeeModule.java
cms/src/main/java/uk/nhs/digital/externalstorage/modules/S3ConnectorServiceRegistrationModule.java
cms/src/test/java/uk/nhs/digital/apispecs/module/ApiSpecSyncFromApigeeModuleTest.java
pom.xml
vars.mk

Also:
* Fixes the `Error while shutting down daemon module
org.onehippo.cms7.services.HippoServiceException:
A service of type uk.nhs.digital.externalstorage
.s3.PooledS3Connector is already registered.`,
where the service was attempted to be registered,
rather than unregistered on module/system shutdown,
by mistake.

[ADZ-987] Defer API Spec batch jobs scheduling

---

repository-data/application/src/main/resources/hcm-config/configuration/modules/diagnostics.yaml
repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml
repository-data/webfiles/package-lock.json
repository-data/webfiles/src/main/resources/site/freemarker/common/api-try-it-now.ftl

Override swagger-ui configuration allows us to hide the try-it-now configurations and enable all input fields for params.

[ADZ-322] Automatic try-it-out trigger

---

repository-data/site/src/main/resources/hcm-config/hst/configurations/common/pages/apispecification.yaml
repository-data/site/src/main/resources/hcm-config/hst/configurations/common/sitemap.yaml
repository-data/site/src/main/resources/hcm-config/hst/configurations/common/templates.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/api-catalogue-preview.ftl

Creating preview page with new templates - Header and Footer. 
Only accessible at api-catalogue/preview.

[ADZ-1178] First version working preview create and base changed

---

cms/src/main/java/uk/nhs/digital/apispecs/handlebars/BorderHelper.java
cms/src/main/java/uk/nhs/digital/apispecs/handlebars/UuidHelper.java
cms/src/main/java/uk/nhs/digital/apispecs/handlebars/schema/IndentationHelper.java
cms/src/main/java/uk/nhs/digital/apispecs/handlebars/schema/SchemaHelper.java
cms/src/main/java/uk/nhs/digital/apispecs/swagger/ApiSpecificationStaticHtml2Codegen.java
cms/src/main/resources/api-specification/codegen-templates/schema.mustache
cms/src/main/resources/api-specification/codegen-templates/schema_object.mustache
cms/src/main/resources/api-specification/codegen-templates/schema_xof_if.mustache
cms/src/main/resources/api-specification/codegen-templates/schema_xof_with.mustache
cms/src/test/java/uk/nhs/digital/apispecs/handlebars/OptionsStub.java
cms/src/test/java/uk/nhs/digital/apispecs/handlebars/schema/BorderHelperTest.java
cms/src/test/java/uk/nhs/digital/apispecs/handlebars/schema/IndentationHelperTest.java
cms/src/test/java/uk/nhs/digital/apispecs/handlebars/schema/SchemaHelperTest.java
cms/src/test/resources/test-data/api-specifications/ApiSpecSyncFromApigeeJobIntegrationTest/oasV3_complete.html
cms/src/test/resources/test-data/api-specifications/SchemaHelperTest/schemaObject-empty.html
cms/src/test/resources/test-data/api-specifications/SchemaHelperTest/schemaObjectCompleteTopLevel-simpleFields.html
cms/src/test/resources/test-data/api-specifications/SchemaHelperTest/schemaObjectsMultiLevelHierarchy-items.html
cms/src/test/resources/test-data/api-specifications/SchemaHelperTest/schemaObjectsMultiLevelHierarchy-xOf.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_complete.html
repository-data/webfiles/src/main/resources/site/src/scss/components/_api-specification.scss

Changes to implement rendering of a tree diagram alongside the schema, to further indicate nesting. Said tree diagram is made up of absolutely-positioned divs, referred to in code as "borders". The tree diagram ties in visually to expander/collapser buttons, which have been moved to the left of the name column. Each indented level has lighting and padding set as CSS vars.
The main bit of work is in introducing the BorderHelper. I have also updated the UUIDHelper to implement the Helper interface, and the IndentationHelper to let it return a weighted indentation value (useful for controlling the amount of padding between 'indentations').

ADZ-895 indicate level of nesting in schema with tree diagram

---

cms/src/test/java/uk/nhs/digital/apispecs/handlebars/schema/SchemaHelperTest.java
cms/src/test/java/uk/nhs/digital/apispecs/swagger/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest.java
cms/src/test/resources/test-data/api-specifications/ApiSpecSyncFromApigeeJobIntegrationTest/oasV3_complete.json
cms/src/test/resources/test-data/api-specifications/SchemaHelperTest/schemaObjectsMultiLevelHierarchy-properties.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_complete.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_complete.json
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_incomplete_no_components-field.html
pom.xml

Recent update of swagger-codegen-generators from
1.0.25 to 1.0.26 broke importing and re-rendering
of API specifications as the new version of the
library was compiled with newer Jackson version.
This commit fixes this by upgrading Jackson dependencies
to corresponding from version 2.11.2 to 2.12.2.
Also:
* In SchemaHelperTest restores a test case previously
deleted by mistake.
* Makes SchemaHelperTest no longer create a temporary
JSON datafile (feeding JSON to parser directly, instead).
* Expands test case
rendersSpecification_whenCompleteOpenApiJsonAsHtml
with data that triggered the (now fixed) bug.

[ADZ-1219] OAS spec import and rerender fix

---

cms/src/test/java/uk/nhs/digital/apispecs/swagger/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest.java
repository-data/README.md
repository-data/local/src/main/resources/hcm-config/configuration/update/ApiSpecificationRenderer/ApiSpecificationRenderer.groovy
repository-data/local/src/main/resources/hcm-config/configuration/update/ApiSpecificationRenderer/ApiSpecificationRenderer.yaml
repository-data/local/src/main/resources/hcm-config/configuration/update/ApiSpecificationRenderer/CodegenRunner.java

We have implemented a solution to automate a manual process. 
The updater editor allows developers to run Groovy updater scripts against a running repository from within the CMS UI. This allows us to update the "frontend" code without restart the server. 
To test run it locally and go to: http://localhost:8080/cms/systemupdater 
Select rerenderScpecs from the list. Update two variables with your local paths and click execute.

ADZ-1243 Updater Script to update nodes.

---

cms/src/main/java/uk/nhs/digital/apispecs/swagger/CodegenDefaultGenerator.java
cms/src/main/java/uk/nhs/digital/apispecs/swagger/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverter.java
cms/src/test/java/uk/nhs/digital/apispecs/handlebars/HeadingsHyperlinksFromMarkdownHelperTest.java
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_operationIdsInVariousFormats.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_operation_with_no_own_parameters.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_operationsTagged.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_operationsTagged.json
repository-data/local/src/main/resources/hcm-config/configuration/update/ApiSpecificationRenderer/ApiSpecificationRenderer.groovy

Re-introduced CodegenDefaultGenerator.java to allow for custom ordering of CodegenOperations. annoyingly, processOperation is a private method so the generator can't just call the super method

[ADZ-769] ADZ-769 implementing mechanism for ordering endpoint headings

---

cms/src/main/java/uk/nhs/digital/apispecs/commonmark/CommonmarkMarkdownConverter.java
cms/src/main/java/uk/nhs/digital/apispecs/commonmark/HeadingAttributeProvider.java
cms/src/main/java/uk/nhs/digital/apispecs/commonmark/ThematicBreakAttributeProvider.java
cms/src/test/java/uk/nhs/digital/apispecs/CommonmarkMarkdownConverterTest.java
cms/src/test/java/uk/nhs/digital/apispecs/commonmark/HeadingAttributeProviderTest.java
cms/src/test/java/uk/nhs/digital/apispecs/commonmark/ThematicBreakAttributeProviderTest.java
cms/src/test/resources/test-data/api-specifications/ApiSpecSyncFromApigeeJobIntegrationTest/oasV3_complete.html
cms/src/test/resources/test-data/api-specifications/CommonmarkMarkdownConverterTest/headings-with-duplicate-values.html
cms/src/test/resources/test-data/api-specifications/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest/oasV3_complete.html

This user story has changed the way we parse the description text of specifications. 
Until now we just manage headers size from markdown. Based on the number of hashes(#) we set a number of attributes implementing `AttributeProvider` interface. However, it has some limitations that don't allow us to have proper control to add new HTML elements like `<hr>`
In order to have full control, I have implemented `NodeRenderer` interface, another interface that allows full control of nodes.
Within these changes I have deleted `HeadingAttributeProvider` class that was an `AttributeProvider` implementation and use the same logic in a new class `HeadingsRenderer` that implements a `NodeRenderer`. Now we have the same logic as before plus the possibility to add new HTML elements.

[ADZ-1312] API-Description - Add horizontal line above <h2> headers

---

acceptance-tests/pom.xml
repository-data/webfiles/src/main/resources/site/freemarker/common/apicatalogue/scrollable-filter-nav.ftl
repository-data/webfiles/src/main/resources/site/src/scss/rebrand/components/_api-catalogue.scss

Category headings in API catalogue's _Filters_
section are now styled in line with the Design
System > Filter Menu Section.
Also, implements [ADZ-1376] '_API Catalogue -
Side Nav Refinement (Filters to remain
expanded when selected)_'.

[ADZ-1365] API catalogue categories restyle

---

repository-data/webfiles/src/main/resources/site/freemarker/common/apicatalogue/scrollable-filter-nav.ftl
repository-data/webfiles/src/main/resources/site/src/scss/rebrand/components/_api-catalogue.scss

Updating the filters in the sidenav
- Increased vertical spacing between filters
- Re-implemented checkbox border on hover, reduced border size
- Changed filter text colour

[ADZ-1358] filter refinement

---

conf/query/lucene/indexing_configuration.xml

All properties of documents of type `website:apispecification` used to be indexed by default.
This change limits indexing on local machines only to relevant ones (actual goal: exclude `website:html` one from indexing).

[ADZ-1495] Exclude API spec HTML from Lucene

---

repository-data/development/src/main/resources/hcm-content/content/documents/administration/developer-hub.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/apicatalogue/api-catalogue-entries.ftl
site/components/src/main/java/uk/nhs/digital/common/components/apicatalogue/filters/Filters.java
site/components/src/main/java/uk/nhs/digital/common/components/apicatalogue/filters/Subsection.java
site/components/src/test/java/uk/nhs/digital/common/components/apicatalogue/filters/FiltersTest.java
site/components/src/test/java/uk/nhs/digital/common/components/apicatalogue/filters/FiltersTestUtils.java
site/components/src/test/java/uk/nhs/digital/common/components/apicatalogue/filters/JacksonFiltersFactoryTest.java

Adds functionality to mark filters with a highlight colour which changes the filter background and makes them show above the API Name.
Screenshot showing Inpatient filter highlighted in light-red and Outpatient filter highlighted in light-blue:

[ADZ-1411] Added support for highlighting filters 

---

repository-data/application/src/main/resources/hcm-config/configuration/modules/crispregistry.yaml
site/components/src/main/resources/META-INF/hst-assembly/addon/crisp/overrides/custom-resource-resolvers.xml
site/components/src/main/resources/META-INF/hst-assembly/overrides/application-secrets.xml

I have also removed `crisp:sitescopes` as this is not needed in a single site project.

[DW-2820] Remove Gov Delivery Bean from the Site context

---

repository-data/site/src/main/resources/hcm-config/hst/configurations/common/sitemap.yaml

Disables First Level Page Caching for the purpose of collecting garbage collection logs so that the impact of First Level Page Caching on garbage collection can be better assessed.

[ADZ-1926] Disables First Level Page Cache

---

repository-data/site/src/main/resources/hcm-config/hst/configurations/common/sitemap.yaml

First Level Page Cache (FLPC) was temporarily disabled
for the content of `/developer/api-catalogue` in
commit `597485b0` for testing of impact of FLPC
on garbage collection performance.
This change reverts that commit, re-enabling
First Level Page Caching for content of
`/developer/api-catalogue` (with the exclusion
of API catalogue page itself - as it was
previously).

[ADZ-1926] Re-enables First Level Page Cache

---

pom.xml
src/main/assembly/shared-lib-component.xml

https://nhsd-jira.digital.nhs.uk/browse/ADZ-2397
https://github.com/NHS-digital-website/hippo/pull/2179/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8
seems to have upgraded the versions of okhttp and okio to the latest, but they are incompatible with each other. okio doesn't have any security advisories so the current version should be fine for dependabot.
The Kotlin standard library is required for the new version of okhttp.
I'm not really sure why we have to handle transitive dependencies manually as I'm not too familiar with Maven and Tomcat. We don't seem to use okhttp or okio directly but we have direct dependencies on them. If I remove them to let Maven handle it they just don't get pulled in.

Adz 2397 splunk logging

---

repository-data/webfiles/src/main/resources/site/freemarker/common/apispecification.ftl

[ADZ-2495](https://nhsd-jira.digital.nhs.uk/browse/ADZ-2495)

[ADZ-2495] Update OAS CTA wording so no longer truncated

---

site/components/src/main/java/uk/nhs/digital/common/components/apispecification/swagger/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverter.java
site/components/src/test/java/uk/nhs/digital/common/components/apispecification/swagger/SwaggerCodeGenOpenApiSpecificationJsonToHtmlConverterTest.java

Config can cause circular schema refs to infinitely recurse.

[ADZ-2685] Revert rendering config

---

conf/log4j2-dist.xml

@GeoffreyHayward  it did not quite stop the org.hippoecm.hst.servlet.HstFreemarkerServlet warnings, I think this might be because it is a servlet rather than freemarker. I have added an extra error line for this.
If you could do the honors... and I will check again on UAT.
Thanks.

[DW-000] Change freemarker servlet to error only

---

repository-data/site/src/main/resources/hcm-config/hst/configurations/common/prototypepages/general.yaml

Go to Experience Manager > Choose Page menu on the top > New > Create page
You should be seeing an empty page with containers available for components

[DW-3368] Add prototype page configuration for general pages

---

repository-data/webfiles/src/main/resources/site/apispecification/rapidoc-customisation.js

RapiDoc `spec-loaded` event doesn't actually mean it's quite loaded yet and the page isn't rendered.

[ADZ-0000] Delay customisations on load

---

repository-data/application/src/main/resources/hcm-config/namespaces/website/apispecification.yaml
repository-data/webfiles/src/main/resources/site/freemarker/common/apispecification.ftl

Done following the 19/05 RapiDoc migration deadline to try to prevent new specs from using the old renderer

[AMP-1598] set enableRapiDoc flag to default to true

---

repository-data/site/src/main/resources/hcm-config/hst/configurations/common/sitemap.yaml

I had set the relative content path for services as well as just Service catalogue in my previous PR AMP-1816.

[AMP-1816] Correct content path for services

---

repository-data/site/src/main/resources/hcm-config/hst/configurations/common/sitemap.yaml

Follow up to https://github.com/NHS-digital-website/hippo/pull/2534 since it did not sort the problem. Have just totally reverted the content path changes I made for now.

[AMP-1816] Revert changes to content paths

---

.github/workflows/deploy-to-production--stage-1.yml
.github/workflows/deploy-to-production--stage-2.yml

Since renaming the 2 workflows, Github seems to be reporting an unconnected issue with them. By duplicating the files, they are seen as new files on Github.

[DW-3424] Replace stuck workflows

---

acceptance-tests/pom.xml
cms/src/main/java/uk/nhs/digital/apispecs/services/auth/ProxygenJwtClientAuthenticationHandler.java
cms/src/main/resources/META-INF/hst-assembly/addon/crisp/overrides/custom-resource-resolvers.xml
cms/src/test/java/uk/nhs/digital/apispecs/jobs/ApiSpecSyncFromApigeeJobIntegrationTest.java
cms/src/test/java/uk/nhs/digital/apispecs/jobs/ApiSpecSyncFromProxygenJobIntegrationTest.java
pom.xml

Getting an access token for use in a call to get proxygen specs is failing. Seems like this is due to a missing KID header.
Have already updated the config properties for UAT and CS environments in testing. Need to update production config in order for this to work upon deployment.

AMP-1861-proxygen-auth-issue

---

repository-data/webfiles/src/main/resources/site/apicatalogue/apicatalogue.js

For the search in API and Service catalogues tags will now be included as part of the search parameter matching for items in the list.
There don't seem to be any tests around these functions so I can add them perhaps.

[AMP-1878] Catalogue search will include tags

---

acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/pages/site/SitePage.java
acceptance-tests/src/test/java/uk/nhs/digital/ps/test/acceptance/steps/site/SiteSteps.java
acceptance-tests/src/test/resources/features/site/apiCatalogue.feature
repository-data/webfiles/src/main/resources/site/freemarker/common/catalogue/scrollable-filter-nav.ftl

In the API and Service catalogues there exists and issue in which the auto tooltip to display title text for the anchor elements of the filters is covering the pop-up description text.
Have set aria-label instead of title to preserve accessibility for screen readers.

[AMP-1708] Stop tooltip from blocking filter description

---

repository-data/webfiles/src/main/resources/site/freemarker/common/catalogue/catalogue.ftl

[Ticket](https://nhsd-jira.digital.nhs.uk/browse/AMP-1377)
Issue identified with Safari browser in which the 'Include retired APIs and API standards' toggle is not updating the page url and refreshing. This is not and issue for other browsers tested.

[AMP-1377]-safari-retired-filter-toggle-issue

---

repository-data/webfiles/src/main/resources/site/freemarker/common/catalogue/scrollable-filter-nav.ftl
site/components/src/main/java/uk/nhs/digital/common/components/catalogue/CatalogueLink.java
site/components/src/main/java/uk/nhs/digital/common/components/catalogue/filters/Filters.java
site/components/src/main/java/uk/nhs/digital/common/components/catalogue/filters/FiltersAndLinks.java
site/components/src/main/java/uk/nhs/digital/common/components/catalogue/filters/NavFilter.java
site/components/src/main/java/uk/nhs/digital/common/components/catalogue/filters/Section.java
site/components/src/main/java/uk/nhs/digital/common/components/catalogue/filters/StatusUpdatingFilterVisitor.java
site/components/src/test/java/uk/nhs/digital/common/components/catalogue/ApiCatalogueComponentTest.java
site/components/src/test/java/uk/nhs/digital/common/components/catalogue/ServiceCatalogueComponentTest.java
site/components/src/test/java/uk/nhs/digital/common/components/catalogue/filters/FiltersAndLinksTests.java
site/components/src/test/java/uk/nhs/digital/common/components/catalogue/filters/FiltersTest.java
site/components/src/test/java/uk/nhs/digital/common/components/catalogue/filters/StatusUpdatingFilterVisitorTest.java

[Ticket](https://nhsd-jira.digital.nhs.uk/browse/AMP-1880)
Link counts for the filters in the Nav bar of the Service and API Catalogues.
These counts follow a similar logic to the filter items themselves, i.e. the count will represent the number of catalogue links considering the AND/OR logic within or outside a Section.

Amp 1880 counts on filters

---

site/components/src/main/java/uk/nhs/digital/common/components/catalogue/CatalogueComponent.java
site/components/src/main/java/uk/nhs/digital/common/components/catalogue/CatalogueLink.java
site/components/src/main/java/uk/nhs/digital/website/beans/Internallink.java
site/components/src/test/java/uk/nhs/digital/common/components/catalogue/ApiCatalogueComponentTest.java
site/components/src/test/java/uk/nhs/digital/common/components/catalogue/ServiceCatalogueComponentTest.java

[Ticket](https://nhsd-jira.digital.nhs.uk/browse/AMP-2109)
Documents that are part of the catalogue link lists when unpublished would cause the catalogue to break. This change will check to see if a document has a visible node and is published before including it in the catalogue.

[AMP-2109] Check if published

---

cms/src/main/java/uk/nhs/digital/common/listeners/CyberAlertListener.java
cms/src/main/java/uk/nhs/digital/common/listeners/PreReleaseKeyListener.java
site/components/src/main/java/uk/nhs/digital/common/components/HeroComponent.java
site/components/src/main/java/uk/nhs/digital/ps/components/DatasetComponent.java
site/components/src/test/java/uk/nhs/digital/intranet/valves/AccessTokenValveTest.java

-  uk.nhs.digital.ps.components.DatasetComponent
- uk.nhs.digital.common.components.HeroComponent
- uk.nhs.digital.common.listeners.PreReleaseKeyListener
- uk.nhs.digital.common.listeners.CyberAlertListener
Also, sets all of the tests in AccessTokenValueTest to @ignore as they are stopping the pipeline, and are earmarked for deletion in a follow-up ticket.

[DW-3649] Removes NullPointerExceptions cases

---

repository-data/webfiles/src/main/resources/site/apispecification/rapidoc-min.js

In the API specification document, indication of mandatory fields has been changed from red asterisk(*) to the wording - 'required' (added the word).
1. The word 'required' has been added in red font in all the individual mandatory field instead of  '*' in red font.
2. The word 'required' has been added in red font in all the Request Path parameters, request and response headers section  instead of '*' in red font.(please see the attachment)
Since the change is in rapidoc-min.js minified file, please review the actual code change in hippo-rapidoc repository, please find the PR - https://github.com/NHS-digital-website/hippo-RapiDoc/pull/11

[AMP-2837] Rapidoc changes to add the word required

---

site/components/src/main/java/uk/nhs/digital/common/components/catalogue/ApiCatalogueEssentialsFacetsComponent.java

Given the context and the OOM report, this ConcurrentHashMap was likely overkill, using up memoery without need.

[WSP-167] Changes a ConcurrentHashMap to HashMap

---

cms/src/main/java/uk/nhs/digital/ps/PublicationAccessibilityUpdateJob.java
cms/src/test/java/uk/nhs/digital/ps/PublicationAccessibilityUpdateJobTest.java

Before the fix
- It would not retry to update the document if, for any reason, the job failed; now, it will try again the time the job runs.
- The whole job would halt if any document had an unmerged edit; now, it will continue to the next document.
**Now, safely, documents that have unmerged edits will continue to fail until a content editor has approved the changes. But this will no longer fail the whole job.** Once the document has been merged or reverted, the next run will pick it up correctly. 
As well as the fix, I have added:
- For future maintenance, comments that explain the code.
- Unit tests

[WSP-396] Publication job fix
